package com.example.project.Constants

object Constants {
    const val ACTION_SET_EXACT_ALARM = "ACTION_SET_EXTRA"
    const val EXTRA_EXACT_ALARM_TIME = "EXTRA_EXACT_ALARM_TIME"

    const val SET_EXAM_NOTIFICATION = "SET_EXAM_NOTIFICATION"
    const val SET_EVENT_NOTIFICATION = "SET_EVENT_NOTIFICATION"
    const val SET_REMINDER_NOTIFICATION = "SET_REMINDER_NOTIFICATION"
}